# Generated by Django 5.0.14 on 2026-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(default='CC78504689', max_length=10, unique=True),
        ),
    ]
