# Generated by Django 5.0.14 on 2026-09-09 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.PositiveIntegerField()),
                ('is_sleeper', models.BooleanField(default=False)),
                ('is_ac', models.BooleanField(default=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bus Type',
                'verbose_name_plural': 'Bus Types',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
                ('seat_layout', models.JSONField(default=dict, help_text='JSON seat layout configuration')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bus_images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('is_live_trackable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to=settings.AUTH_USER_MODEL)),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='buses.bustype')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('seat_type', models.CharField(choices=[('seater', 'Seater'), ('sleeper', 'Sleeper'), ('window', 'Window'), ('aisle', 'Aisle')], default='seater', max_length=20)),
                ('deck', models.PositiveIntegerField(default=1, help_text='1 for lower deck, 2 for upper deck')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('is_window', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'unique_together': {('bus', 'seat_number')},
            },
        ),
    ]
