# Generated by Django 5.0.14 on 2026-09-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, default=0, help_text='Speed in km/h', max_digits=6)),
                ('heading', models.DecimalField(decimal_places=2, default=0, help_text='Direction in degrees', max_digits=5)),
                ('current_stop', models.CharField(blank=True, max_length=100)),
                ('next_stop', models.CharField(blank=True, max_length=100)),
                ('estimated_arrival', models.TimeField(blank=True, null=True)),
                ('is_on_time', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='buses.bus')),
            ],
            options={
                'verbose_name': 'Bus Location',
                'verbose_name_plural': 'Bus Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('current_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='buses.bus')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Tracking Session',
                'verbose_name_plural': 'Tracking Sessions',
            },
        ),
    ]
